kind: PersistentVolume
apiVersion: v1
metadata:
  name: datadir-kafka-0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/jordanwalker/Code/reference-architecture/cloud-native/kubernetes/minikube/kubeless/data"
