kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeeper-zoo-0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/jordanwalker/Code/reference-architecture/cloud-native/kubernetes/minikube/kubeless/data"
  resources:
    requests:
      storage: 3Gi
  
